RailsApp/config/routes.rb
RailsApp::Application.routes.draw do

  get "map/index" => 'map#index', as: :map
  resources :routes

  resources :locations
  
  post "companies/new" => 'companies#new', as: :new_company_path
  resources :companies

  get "static/index"
  get 'static/about' => 'static#about', as: :about

  post "/admin/users/new" => 'admin/users#new'
  
  resources :accounts
  
  devise_for :users, :controllers => { registrations: 'users/registrations' } 
  
  namespace :admin do
    get '/' => 'users#index'

    resources :users
  end  
  
  namespace :manager do
    get '/' => 'users#index'

    resources :users
  end  
  post "/manager/users/new" => 'manager/users#new'
  
  resources :accounts do
      collection { post :search, to: 'accounts#index' }
  end 

 
  resources :route_stops
  controller :route_stops do
    post 'route_stops/new', :action =>  'new'
  end

  post "/users/location", to: 'admin/users#location'
  post "/map/users/location", to: 'admin/users#location'
  

  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'
     

  root 'static#index'
  

  

end

RailsApp/app/models/route.rb
# defines a route and its relation to other objects
class Route < ActiveRecord::Base
  belongs_to :user
  belongs_to :company


  # Gets the locations of route stops belonging to this route and returns them in JSON format
  def get_locations
  	locations = Array.new

  	# Find all of the route stops with this route id
  	@stops = RouteStop.find(:all, :conditions => [ "route_id = ?", self.id])

  	@stops.each do |stop|
  		# Push the location from the route stop itself
  		locations.push stop.get_location
  	end

  	# Hand it back in JSON format
  	locations.to_json
  end
end

RailsApp/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  respond_to :html
  
  # Displays a list of all Routes
  def index
    
    if (params[:user_id] != nil)
          @user = User.find(params[:user_id])
          @search = Route.where('routes.User_id' => params[:user_id]).search(params[:q])
        end
        
        # Check to see if the user is a Administrator , if so show all accounts
        if can? :manage, :all
          if (@search == nil)
            @company = Company.find(current_user.company_id)
            @search = Route.all.search(params[:q])
          end
    
        # Check to see if the user is a Manager, if so show all accounts from company
        elsif can? :manage, Account
          if (@search == nil)
            @company = Company.find(current_user.company_id)
            @search = Route.where('routes.Company_id' => current_user.company_id).search(params[:q])
          end
            
        #otherwise show only my account info.
        else 
          @user = User.find(current_user.id)
          @search = Route.where('routes.User_id' => current_user.id).search(params[:q])
        end
    
        @routes = @search.result.page(params[:page]).order('created_at DESC')
        
        @search.build_condition
        @search.build_sort if @search.sorts.empty?  
    
          
    respond_with(@routes)
    
    
    
  end
  
  # displays the Route with the given Route ID
  def show
    # show the stops that are part of this route.
    @route_stops = RouteStop.where('route_stops.route_id' => @route.id)
    respond_with(@route)
  end
  
  # Displays the new Route form to allow the user to enter the Route info
  def new
    @route = Route.new
    @users = User.where('users.Company_id' => current_user.company_id)
    respond_with(@route)
  end
  
  # Displays the Route form to allow the user to edit the Account info
  def edit
    @users = User.where('users.Company_id' => current_user.company_id)
  end
  
  # creates a new Route object with the given Parameters
  def create
    @route = Route.new(route_params)
     respond_to do |format|
         if @route.save
           flash[:notice] = flash[:notice].to_a.concat @route.errors.full_messages
            # The system will auto forward user to add a new stop once the route is first created.
           format.html { redirect_to new_route_stop_path(:route_id => @route.id), :notice => 'Route was successfully created.' }
           format.json { render :json => @route, :status => :created, :location => @route }
         else
           flash[:notice] = flash[:notice].to_a.concat @route.errors.full_messages
           format.html { render :action => "new"}
           format.json { render :json => @route.errors, :status => :unprocessable_entity }
         end
       end
  end
  
  # Updates the given Route with the given parameters from the edit form
  def update
    @route.update(route_params)
    respond_with(@route)
  end
  
  # deletes the given Route object and destroys associated route_stops if the route
  # was successfully destroyed
  def destroy
    id = @route.id
    @route.destroy
    if @route.destroyed?
      RouteStop.where(route_id: id).destroy_all
    end
    respond_with(@route)
  end

  private
    def set_route
      @route = Route.find(params[:id])
    end

    def route_params
      params.require(:route).permit(:name, :scheduled, :user_id, :company_id)
    end
end

RailsApp/app/helpers/routes_helper.rb
module RoutesHelper
end

RailsApp/app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :scheduled %><br>
    <%= f.date_select :scheduled %>
  </div>
 <%= f.hidden_field :company_id, :value => current_user.company_id %>
	<% if can? :manage, Account %>
	<div class="field">
    <%= f.label :user_id %><br>
	<%= f.collection_select :user_id, @users, :id, :full_name, include_blank: true %>
  </div>
	<% else %>
	  <%= f.hidden_field :user_id, :value => current_user.id %>
	<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

RailsApp/app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

RailsApp/app/views/routes/index.html.erb
<% if user_signed_in? %>

  <h1>Listing  <%=@routes.count%> route<%if (@routes.count > 1) %>s<% end%> for 
	<% if (@user != nil) %>
 	 	<%= @user.full_name %>
  	 <% else %>
  	 	<%= @company.name %>
  	 <% end %></h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Schedualed</th>
        <th>User</th>
        <th>Company</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @routes.each do |route| %>
        <tr>
          <td><%= route.name %></td>
          <td><%= route.scheduled %></td>
          <td><%= route.user.full_name %></td>
          <td><%= route.company.name %></td>
          <td><%= link_to 'Show', route %></td>
          <td><%= link_to 'Edit', edit_route_path(route) %></td>
          <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= button_tag 'Plot', onclick: 'buildRoute(' + route.get_locations + ')' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
 
  
  <%= button_to "New Route", new_route_path, :method => "get" %>

  <br>

  <div id="map-container" style='width: 800px;'>
    <h1>Map</h1>
    <div id="map-features"><button onclick="clearMap()">Clear Map</button> <button onclick="addSelfMarker()">Plot My Location</button></div>
    <div id="map-canvas" style='width: 947px; height: 500px;'></div>
  </div>

  <div id="direction-container"></div>

<% else %>
  You must be logged in to view this page.
<% end %>


<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBsmPgcigaqDrXUOGT6eNvApO06f_MyIfg"></script>
<script type="text/javascript">
  var map = null;
  var markers = [];
  var directionsDisplay;
  var directionsService = new google.maps.DirectionsService();

  // Initialize Google Maps 
  function initMap() {
    directionsDisplay = new google.maps.DirectionsRenderer();

    var mapOptions = {
      zoom: 4
    };

    var mapElement = document.getElementById('map-canvas');

    // Create the Google Map
    map = new google.maps.Map(mapElement, mapOptions);

    directionsDisplay.setMap(map);
    directionsDisplay.setPanel(document.getElementById('direction-container'));

    // Centers on Atlanta, GA for now
    var pos = new google.maps.LatLng(33.7550, -94.3900);
    map.setCenter(pos);
  }

  // Error handling of the geolocation.
  function handleNoGeolocation(errorFlag) {
    // was geolocation a bust?
    if (errorFlag) {
      var content = 'Error: The Geolocation service failed.';
    } else {
      var content = 'Error: Your browser doesn\'t support geolocation.';
    }
  }

  // Adds a marker to the map with the specified options.
  function addMarker(options) {
    /*
      options = {
        lat: float,
        lng: float,
        pos: google.maps.LatLng(lat, lng),
        icon: url,
        title: 'string'
      }
    */

    var pos = null;
    var marker = null;

    // do we have a google maps position or a lat/lng?
    if(options.lat !== undefined && options.lng !== undefined) {
      pos = new google.maps.LatLng(options.lat, options.lng);
    } else {
      pos = options.pos;
    }

    // what kind of icon should we use?
    // default is a green marker.
    if(options.icon === undefined) {
      marker = new google.maps.Marker({
        position: pos,
        map: map,
        icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png',
        title: options.title
      });
    } else {
      marker = new google.maps.Marker({
        position: pos,
        map: map,
        icon: options.icon,
        title: options.title
      });
    }

    // push the marker to an array for later use.
    markers.push(marker);
  }

 // Adds a marker at your current location, if your computer allows it.
  function addSelfMarker() {
    // Can we get a location?
    if(navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        var lat = position.coords.latitude;
        var lng = position.coords.longitude;

        var pos = new google.maps.LatLng(lat, lng);

        // we'll use a red marker to show our location.
        var options = {
          pos: pos,
          icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png',
          title: 'Your Location'
        }

        //create a new request that we'll make to save the lat/lng
        var x = new XMLHttpRequest();

        //we're going to post some JSON
        x.open('POST', 'users/location/', true);
        x.setRequestHeader('Content-Type', 'application/json');

        //be sure to get all of the CSRF tokens so we can use them in the header
        var metaTags = document.getElementsByTagName('meta');
        for ( var i = 0; i < metaTags.length; i++) { 
          if (metaTags[i].name === 'csrf-token') { 
            x.setRequestHeader('X-CSRF-Token', metaTags[i].content); 
          } 
        }

        //build a data object
        var data = { lat: lat, lng: lng };

        //stringify and send it along
        x.send( JSON.stringify(data) );

        // add the marker and center on it.
        addMarker(options);
      }, function() { handleNoGeolocation(true); });
    } else {
      handleNoGeolocation(false);
    }
  }

  // Sets the map for all markers to null and
  // removes them from the map and the array.
  function clearMarkers() {
    var size = markers.length;
    for(var i=0; i<size; i++) {
      markers[i].setMap(null);
    }

    markers = [];
  }

  // Clears the map of everything and empties the direction-container
  function clearMap() {
    $('#direction-container').html('');
    initMap();
  }

  // Toggles the map hidden or displayed.
  function toggleMap() {
    if($('#map-container').css('display') == "none") {
      $('#map-container').show();
      $('#map-button').html("Hide Map");
    } else {
      $('#map-container').hide();
      $('#map-button').html("Show Map");
    }
  }

  // Builds a route using route stops
  function buildRoute(array) {
    alert("Please wait a few moments while the route gets setup");
    var wayPoints = [];

    clearMarkers();

    //Do something with the array
    for (var i = array.length - 1; i >= 0; i--) {
      var options = { title: array[i].name, lat: array[i].lat, lng: array[i].lng };
      var pos = new google.maps.LatLng(array[i].lat, array[i].lng);
      wayPoints.push({ location: pos, stopover: true });
      addMarker(options);
    };

    // Do we have a location? If so, let's start there.
    if(navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        function(position) {
          var originPoint = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
          var options = { originPoint: originPoint, wayPoints: wayPoints };
          calcRoute(options);
        },
        function() { handleNoGeolocation(true); }
      );
    } else {
      handleNoGeolocation(false);
    }

    clearMarkers();
  }

  // Calculates the route given the waypoints
  // using google's directions service
  function calcRoute(options) {
    /*
      options = {
        originPoint: google.maps.LatLng,
        wayPoints: [google.maps.LatLng]
      }
    */

    // Do we have any waypoints?
    if(options.wayPoints.length > 0) {
      var request = {
        origin: options.originPoint,
        destination: options.originPoint,
        waypoints: options.wayPoints,
        optimizeWaypoints: true,
        travelMode: google.maps.TravelMode.DRIVING
      };

      // Plot the route when we get the OK from google
      directionsService.route(request, function(response, status) {
        if (status == google.maps.DirectionsStatus.OK) {
          directionsDisplay.setDirections(response);
        }
      });
    } else {
      alert('Please add route stops to the route before plotting.');
    }
  }

  // Inittializes the map on page load
  $(function() {
    initMap();
  });
</script>

RailsApp/app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

RailsApp/app/views/routes/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Scheduled:</strong>
  <%= @route.scheduled %>
</p>

<p>
  <strong>User:</strong>
  <%= @route.user.first_name %> <%= @route.user.last_name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @route.company.name %>
</p>
<% if (@route_stops.count >0) %>
<table>
  <thead>
    <tr>
      <th>Route</th>
      <th>Stop</th>
      <th>Account</th>
      <th>Address</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @route_stops.each do |route_stop| %>
      <tr>
        <td><%= link_to route_stop.route.name, route_stop.route %></td>
        <td><%= route_stop.stop %></td>
        <td><%= link_to route_stop.account.name, route_stop.account %> </td>
        <td><%= route_stop.account.full_address %></td>
        <td><%= link_to 'Show', route_stop %></td>
        <td><%= link_to 'Edit', edit_route_stop_path(route_stop) %></td>
        <td><%= link_to 'Destroy', route_stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to 'Add Another Route Stop', new_route_stop_path(:route_id => @route.id) %><br>

<% else %>
This Route has no routes Add some, 
<%= button_to 'Add Route stop', new_route_stop_path(:route_id => @route.id) %><br>

<% end %>

<%= button_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>