RailsApp/config/routes.rb
RailsApp::Application.routes.draw do

  get "map/index" => 'map#index', as: :map
  resources :routes

  resources :locations
  
  post "companies/new" => 'companies#new', as: :new_company_path
  resources :companies

  get "static/index"
  get 'static/about' => 'static#about', as: :about

  post "/admin/users/new" => 'admin/users#new'
  
  resources :accounts
  
  devise_for :users, :controllers => { registrations: 'users/registrations' } 
  
  namespace :admin do
    get '/' => 'users#index'

    resources :users
  end  
  
  namespace :manager do
    get '/' => 'users#index'

    resources :users
  end  
  post "/manager/users/new" => 'manager/users#new'
  
  resources :accounts do
      collection { post :search, to: 'accounts#index' }
  end 

 
  resources :route_stops
  controller :route_stops do
    post 'route_stops/new', :action =>  'new'
  end

  post "/users/location", to: 'admin/users#location'
  post "/map/users/location", to: 'admin/users#location'
  

  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'
     

  root 'static#index'
  

  

end

RailsApp/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Fleet Trackinator</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>


		<h1 id="banner">Fleet Trackinator</h1>
		
		<div class="wrapper">
		
			<div id="navigation_bar">

				<ul id="gen_navigation">
					<li>
						
						<%= link_to 'Home', root_path %>
					</li>
					<li>
						<%= link_to 'About', about_path %>
					</li>
					
					<% if user_signed_in? %>
					<li>
						<%= link_to 'Sales Accounts', accounts_path, 'data-no-turbolink' => true %>
					</li>
						<% if can? :manage, :all %>
						<li>
						<a href="#">Admin<span></span></a><!--add class dropdown hover-->
						<div class="sub_panel hidden">
							<ul>
								<li>
									<%= link_to 'Users', '/admin' %>
								</li>
								<li>
									<%= link_to 'Companies', '/companies' %>
								</li>
								<li>
									<%= link_to 'Dashboard', '/backend' %>
								</li>
							</ul>
						</div>
					</li>
						<% end %>
					
					<% end %>
					 <% if user_signed_in? %>
					<li id="sign_right">
						<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
						<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
						<font color='white'>Logged in as <strong><%= current_user.first_name %></strong>.</font>
					</li>
					<% else %>
					<li>
						<ul id="sign_navigation">
							<li>
								<%= link_to "Login", new_user_session_path, :class => 'login_button'  %>
							</li>
							<li>
								<%= link_to '', new_user_registration_path, :class => 'sign_in_button'  %>
								
							</li>
						</ul>
					</li>
					<% end %>
					
				</ul>

				<div class="clear">

			<div id="formback">
			<body class='<%= controller.controller_name %>'>
				<body class='<%= controller.controller_name %>'>
				<% flash.each do |key, value| %>
			    <div class="alert alert-<%= key %> alert-dismissable">
			        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
			        <%= value %>
			    </div>
				<% end %>
				</div>
			<%= yield %>

			</body>
</html>
</div>

RailsApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Fleet Trackinator</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>


		<h1 id="banner">Fleet Trackinator</h1>
	
		
		<div class="wrapper">
		
			<div id="navigation_bar">

				<ul id="gen_navigation">
					<li>
						
						<%= link_to 'Home', root_path %>
					</li>
					<% if user_signed_in? %>
						<li>
							<%= link_to 'Map', map_path, 'data-no-turbolink' => true %>
						</li>
						<li>
							<%= link_to 'Sales Accounts', accounts_path, 'data-no-turbolink' => true %>
						</li>
						<li>
							<%= link_to 'Routes', routes_path, 'data-no-turbolink' => true %>
						</li>
					<% else %>
					<li>
						<%= link_to 'About', about_path %>
					</li>
					<% end %>
					<% if can? :manage, :all %>
						<li>
						<a href="#">Admin<span></span></a><!--add class dropdown hover-->
						<div class="sub_panel hidden">
							<ul>
								<li>
									<%= link_to 'Users', '/admin' %>
								</li>
								<li>
									<%= link_to 'Companies', '/companies' %>
								</li>
								
								<li>
									<%= link_to 'Dashboard', '/backend' %>
								</li>
							</ul>
						</div>
					</li>
					<% end %>
					<% else if can? :manage, Users and !can? :manage, :all %>
						<li>
						<a href="#">Manage<span></span></a><!--add class dropdown hover-->
						<div class="sub_panel hidden">
							<ul>
								<li>
									<%= link_to 'Users', '/manager' %>
								</li>
							</ul>
						</div>
					</li>
					<% end %>
					 <% if user_signed_in? %>
					<li id="right">
						<%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link' %> |
						<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> |
						
						<font color='white'>Logged in as <strong><%= current_user.first_name %></strong></font>
					</li>
					<% else %>
					<li>
						<ul id="sign_navigation">
							<li>
								<%= link_to "Login", new_user_session_path, :class => 'login_button'  %>
							</li>
							<li>
								<%= link_to '', new_user_registration_path, :class => 'sign_in_button'  %>
								
							</li>
						</ul>
					</li>
					<% end %>
					
				</ul>

				<div class="clear">

			<div id="formback">
			<body class='<%= controller.controller_name %>'>
				<% flash.each do |key, value| %>
			    <div class="alert alert-<%= key %> alert-dismissable">
			        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
			        <%= value %>
			    </div>
				<% end %>
				</div>
			<%= yield %>

			</body>
</html>
</div>