RailsApp/config/routes.rb
RailsApp::Application.routes.draw do

  get "map/index" => 'map#index', as: :map
  resources :routes

  resources :locations
  
  post "companies/new" => 'companies#new', as: :new_company_path
  resources :companies

  get "static/index"
  get 'static/about' => 'static#about', as: :about

  post "/admin/users/new" => 'admin/users#new'
  
  resources :accounts
  
  devise_for :users, :controllers => { registrations: 'users/registrations' } 
  
  namespace :admin do
    get '/' => 'users#index'

    resources :users
  end  
  
  namespace :manager do
    get '/' => 'users#index'

    resources :users
  end  
  post "/manager/users/new" => 'manager/users#new'
  
  resources :accounts do
      collection { post :search, to: 'accounts#index' }
  end 

 
  resources :route_stops
  controller :route_stops do
    post 'route_stops/new', :action =>  'new'
  end

  post "/users/location", to: 'admin/users#location'
  post "/map/users/location", to: 'admin/users#location'
  

  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'
     

  root 'static#index'
  

  

end

RailsApp/app/models/user.rb
# defines a User and its relations to other objects
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_paper_trail
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_and_belongs_to_many :roles
  belongs_to :company
  has_many :account
  
  before_save :setup_role
  paginates_per 15
  
  
  #geocoded_by :current_sign_in_ip,
  #  :latitude => :lat, :longitude => :lon
  #after_validation :geocode 

  # returns the defined role of the given User
  def role?(role)
      return !!self.roles.find_by_name(role.to_s.camelize)
  end

  # Default role is "User"
  def setup_role 
    if self.role_ids.empty?     
      self.role_ids = [3] 
    end
  end
  
  # returns the full name first and last of the given User  
  def full_name
    "#{self.first_name} #{self.last_name}" 
  end

  # returns the location history of the user
  def location_history
    @locations = Location.where('user_id=?', id).order('created_at desc').all()
  end
  
  
end

RailsApp/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_and_authorize_resource skip_load_resource only: [:create] 
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  before_filter do
      resource = controller_name.singularize.to_sym
      method = "#{resource}_params"
      params[resource] &&= send(method) if respond_to?(method, true)
  end
    
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all.page(params[:page]).order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.attributes = params[:user]
    @user.role_ids = params[:user][:role_ids] if params[:user]
    respond_to do |format|
      if @user.save
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { redirect_to admin_users_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { render :action => "new"}
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end
 
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_users_path, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.json { head :ok }
    end
  end

  # Sets the current users location
  def location
    # Get the current user
    @user = current_user
    
    # Update the users longitude and the latitude from the parameters
    @user.update_attribute(:latitude, params[:lat])
    @user.update_attribute(:longitude, params[:lng])
    
    if(params[:lat] != nil)
      @location = Location.new
      @location.user_id = current_user.id
      @location.company_id = current_user.company_id
      @location.latitude = @user.latitude
      @location.longitude =@user.longitude
      @location.save
    end
  end

  private
  def set_user
      @user = User.find(params[:id])
    end
  
  def user_params
   params.require(:user).permit(:id, :authenticity_token, :first_name, :last_name, :email, :password, :company_id, :password_confirmation, :current_password, :role_ids => [])
  end
end

RailsApp/app/controllers/manager/manager_controller.rb
class Manager::ManagerController < ApplicationController
    before_filter :verify_manager
    
    # Redirects user to Index page unless authenticated as having admin role
    def verify_manager
      :authenticate_user!
      redirect_to root_url unless has_role?(current_user, 'manager')
    end
    
    # defines current_ability for user as ManagerAbility
    def current_ability
      @current_ability ||= ManagerAbility.new(current_user)
    end
end

RailsApp/app/controllers/manager/users_controller.rb
class Manager::UsersController < Manager::ManagerController
  load_and_authorize_resource skip_load_resource only: [:create] 
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :html

  
  before_filter do
      resource = controller_name.singularize.to_sym
      method = "#{resource}_params"
      params[resource] &&= send(method) if respond_to?(method, true)
  end
    
  
  # GET /users
  # GET /users.json
  def index
    @users = User.where('company_id' => current_user.company_id).page(params[:page]).order('created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @locations = Location.where('user_id=?', @user.id).page(params[:page]).order('created_at DESC')
    @user = User.find(params[:id])
    @accounts = Account.where('accounts.User_id' => @user.id).count
    @routes =  Route.where('routes.User_id' => @user.id).count 
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.attributes = params[:user]
    @user.role_ids = params[:user][:role_ids] if params[:user]
    respond_to do |format|
      if @user.save
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { redirect_to manager_users_path, :notice => 'User was successfully created.' }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        flash[:notice] = flash[:notice].to_a.concat @user.errors.full_messages
        format.html { render :action => "new"}
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
    end
 
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to manager_users_path, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to manager_users_url }
      format.json { head :ok }
    end
  end

  # Sets the current users location
  def location
    # Get the current user
    @user = current_user

    # Update the users longitude and the latitude from the parameters
    @user.update_attribute(:latitude, params[:lat])
    @user.update_attribute(:longitude, params[:lng])
  end
  
  private
  def set_user
      @user = User.find(params[:id])
    end
  
  def user_params
   params.require(:user).permit(:id, :authenticity_token, :first_name, :last_name, :email, :password, :company_id, :password_confirmation, :current_password, :role_ids => [])
  end
end

RailsApp/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

RailsApp/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

RailsApp/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

RailsApp/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :company_id)
    end
  
  def account_update_params
      params.require(:user).permit(:first_name, :last_name, :role_ids, :email, :password, :password_confirmation, :current_password, :company_id)
  end
end

RailsApp/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

RailsApp/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

RailsApp/app/views/manager/users/_form.html.erb
<div class="field">
	<%= f.label :first_name %>
	<br>
	<%= f.text_field :first_name %>
</div>

<div class="control-group">
	<%= f.label :last_name %>
	<br>
	<%= f.text_field :last_name %>
</div>

<div class="control-group">
	<%= f.label :email, t("activerecord.attributes.user.email", :default => "Email"), :class => 'control-label' %>
	<div class="input">
		<%= f.text_field :email, :class => 'text_field' %>
	</div>
</div>

<div class="control-group">
	<%= f.label :password, t("activerecord.attributes.user.password", :default => "password"), :class => 'control-label' %>
	<div class="input">
		<%= f.password_field :password, :class => 'password_field' %>
	</div>
</div>
<div class="control-group">
	<%= f.label :Password, t("activerecord.attributes.user.password_confirmation", :default => "password_confirmation"), :class => 'control-label' %>
	<div class="input">
		<%= f.password_field :password_confirmation, :class => 'password_field' %>
	</div>
</div>
<div class="field">
	<%= f.hidden_field :company_id, :value => current_user.company_id %>
	<% if current_user.role? :admin %>
	<div class="field">
		<%= f.label :company_id %>
		<br>
		<%= f.collection_select :company_id, Company.all, :id, :name, include_blank: true %>
	</div>
	<% else %>
	<%= f.hidden_field :company_id, :value => current_user.company_id %>
	<% end %>
</div>
<% for role in Role.where.not(id: 1) %>
<div class ="control-group">
	<%= f.label role.name , :class => 'control-label' %>
	<div class="controls">
		<%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
	</div>
</div>
<% end %>

<div class="form-actions">
	<button class="btn primary" type="submit">
		Save
	</button> or
	<%= link_to "Cancel", admin_users_path %>
</div>

RailsApp/app/views/manager/users/edit.html.erb
<%= form_for [:manager, @user], :url => manager_user_path(@user), :html => { :class => "form-horizontal", :id => "edit_user" } do |f| -%>
  <input name="_method" type="hidden" value="put" />
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

RailsApp/app/views/manager/users/index.html.erb
<h1>Users</h1>
<table class="table table-striped">
 <thead>
  <tr>
    <th>ID</th>
	<th> Name </th>
     <th>
      <%= t("activerecord.attributes.user.email", :default => t("activerecord.labels.email", :default => "Email")) %>
    </th>
    <th>Sales <Br>Accounts</th>
    <th>Routes</th>
    <th>Created at</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| -%>
  <% @accounts = Account.where('accounts.User_id' => user.id).count 
  	@routes =  Route.where('routes.User_id' => user.id).count %>
   <tr class="<%= cycle('list_line_odd', 'list_line_even')%>">
    <td><%= user.id %></td>
    <td><%= user.first_name %> <%= user.last_name %></td>
        <td><%= link_to user.email, manager_user_path(user) %>
    </td>
    <td align ='center'> <%= link_to @accounts, accounts_path(:user_id => user.id) %></td>
    <td align ='center'> <%= link_to @routes, routes_path(:user_id => user.id) %></td>
    <td><%= user.created_at %></td>
    <td>
      <%= link_to "Show", manager_user_path(user), 'data-no-turbolink' => true %>
      <%= link_to "Edit", edit_manager_user_path(user) %>
      <%= link_to "Destroy", manager_user_path(user), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
    </td>
    </tr>
    <% end -%>
   </tbody>
</table>
 <%= paginate @users %>

<%= button_to "New User", new_manager_user_path, :class => 'btn btn-primary' %>

RailsApp/app/views/manager/users/new.html.erb
<%= form_for [:manager, @user], :url => manager_users_path, :html => { :class => :form } do |f| -%>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end -%>

RailsApp/app/views/manager/users/show.html.erb
<h1>Account info for: <%= @user.first_name %> <%= @user.last_name %></h1>
<p><b>Email:</b><%= @user.email %></p>
<p><b>Amount of Accounts</b> = <%= @accounts %>  
<% if (@accounts >0 ) %>
	<%= link_to "View Accounts", accounts_path(:user_id => @user.id), :class => 'btn' %>
<% end %></p>
<p><b>Amount of Routes</b> = <%= @routes %>  
<% if (@routes >0 ) %>
	<%= link_to "View Routes", routes_path(:user_id => @user.id), :class => 'btn' %>
<% end %></p>


<table>
	<thead>
		<tr>
			<th>Latitude</th>
			<th>Longitude</th>
			<th>Timestamp</th>
		</tr>
	</thead>

	<tbody>
	<% @locations.each do |location| %>
		<tr class="<%= cycle('list_line_odd', 'list_line_even')%>">
			<td><%= location.latitude %></td>
			<td><%= location.longitude %></td>
			<td><%= location.created_at.in_time_zone('Eastern Time (US & Canada)').strftime("%A %m-%d-%Y %H:%M:%S") %></td>
			<td>
            <% if location.has_valid_location? %>
              <%= button_tag 'Plot', onclick: 'addMarker({' + location.get_click + '})' %>
            <% else %>
              Bad Location!
            <% end %>
          </td>
		</tr>
	<% end %>
	</tbody>
</table>
<%= paginate @locations %>
<div class="form-actions">
<%= link_to "Back", manager_path, :class => 'btn'  %>
<%= button_tag 'Plot Recent', onclick: 'buildRoute(' + @locations.to_json + ')' %>
</div>

<br>
<div id="map-container" style='width: 800px;'>
<div id="map-canvas" style='width: 947px; height: 500px;'></div>
<div id="map-features"><button onclick="clearMarkers();clearMap();">Clear Map</button></div>


<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBsmPgcigaqDrXUOGT6eNvApO06f_MyIfg"></script>
<script type="text/javascript">
  var map = null;
  var markers = [];
  var directionsDisplay;
  var directionsService = new google.maps.DirectionsService();

  // Initialize Google Maps 
  function initMap() {
    directionsDisplay = new google.maps.DirectionsRenderer();

    // Basic options for a simple Google Map
    var mapOptions = {
      zoom: 4
    };

    var mapElement = document.getElementById('map-canvas');

    // Create the Google Map
    map = new google.maps.Map(mapElement, mapOptions);
    directionsDisplay.setMap(map);

    // Centers on Atlanta, GA for now
    var pos = new google.maps.LatLng(33.7550, -94.3900);
    map.setCenter(pos);
  }

  // Error handling of the geolocation.
  function handleNoGeolocation(errorFlag) {
    // was geolocation a bust?
    if (errorFlag) {
      var content = 'Error: The Geolocation service failed.';
    } else {
      var content = 'Error: Your browser doesn\'t support geolocation.';
    }
  }

  // Adds a marker to the map with the specified options.
  function addMarker(options) {
    /*
      options = {
        lat: float,
        lng: float,
        pos: google.maps.LatLng(lat, lng),
        icon: url,
        title: 'string'
      }
    */

    var pos = null;
    var marker = null;

    // do we have a google maps position or a lat/lng?
    if(options.lat !== undefined && options.lng !== undefined) {
      pos = new google.maps.LatLng(options.lat, options.lng);
    } else {
      pos = options.pos;
    }

    // what kind of icon should we use?
    // default is a green marker.
    if(options.icon === undefined) {
      marker = new google.maps.Marker({
        position: pos,
        map: map,
        icon: 'http://maps.google.com/mapfiles/ms/icons/green-dot.png',
        title: options.title
      });
    } else {
      marker = new google.maps.Marker({
        position: pos,
        map: map,
        icon: options.icon,
        title: options.title
      });
    }

    // push the marker to an array for later use.
    markers.push(marker);
  }

  // Sets the map for all markers to null and
  // removes them from the map and the array.
  function clearMarkers() {
    var size = markers.length;
    for(var i=0; i<size; i++) {
      markers[i].setMap(null);
    }

    markers = [];
  }

  // Builds a route using route stops
  function buildRoute(array) {

  if(array.length === 0) {
    alert("Sorry, there are no recent locations for this user.");
  } else if(array.length === 1) {
    alert("Only one recent location for this user.");
    addMarker({
      lat: array[0].latitude,
      lng: array[0].longitude,
      icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png',
      title: '1'
    });
  } else {
    alert("Please wait a few moments while the route gets setup");
    var wayPoints = [];
    var destinationPoint = new google.maps.LatLng(array[0].latitude, array[0].longitude);
    var originPoint = new google.maps.LatLng(array[array.length-1].latitude, array[array.length-1].longitude);

    clearMarkers();

      //Do something with the array
      var arrayLength = array.length < 10 ? array.length : 10;
      for (var i = arrayLength - 2; i > 0; i--) {
        var options = { title: '' + i, lat: array[i].latitude, lng: array[i].longitude };
        var pos = new google.maps.LatLng(array[i].latitude, array[i].longitude);
        wayPoints.push({ location: pos, stopover: true });

        addMarker(options);
      };

      // Do we have a location? If so, let's start there.
      if(navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(
          function(position) {

            var options = { 
              originPoint: originPoint, 
              destinationPoint: destinationPoint, 
              wayPoints: wayPoints 
            };

            calcRoute(options);
          },
          function() { handleNoGeolocation(true); }
        );
      } else {
        handleNoGeolocation(false);
      }

      clearMarkers();
  }
  }

  // Calculates the route given the waypoints
  // using google's directions service
  function calcRoute(options) {
    /*
      options = {
        originPoint: google.maps.LatLng,
        destinationPoint: google.maps.LatLng,
        wayPoints: [google.maps.LatLng]
      }
    */

    // Do we have any waypoints?
    var request = {
      origin: options.originPoint,
      destination: options.destinationPoint,
      waypoints: options.wayPoints,
      optimizeWaypoints: false,
      travelMode: google.maps.TravelMode.DRIVING
    };

    // Plot the route when we get the OK from google
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
      }
    });
  }

  // Clears the map of everything and empties the direction-container
  function clearMap() {
    initMap();
  }

  // Initializes the map
  $(function() {
    initMap();
  });
</script>