RailsApp/config/routes.rb
RailsApp::Application.routes.draw do

  get "map/index" => 'map#index', as: :map
  resources :routes

  resources :locations
  
  post "companies/new" => 'companies#new', as: :new_company_path
  resources :companies

  get "static/index"
  get 'static/about' => 'static#about', as: :about

  post "/admin/users/new" => 'admin/users#new'
  
  resources :accounts
  
  devise_for :users, :controllers => { registrations: 'users/registrations' } 
  
  namespace :admin do
    get '/' => 'users#index'

    resources :users
  end  
  
  namespace :manager do
    get '/' => 'users#index'

    resources :users
  end  
  post "/manager/users/new" => 'manager/users#new'
  
  resources :accounts do
      collection { post :search, to: 'accounts#index' }
  end 

 
  resources :route_stops
  controller :route_stops do
    post 'route_stops/new', :action =>  'new'
  end

  post "/users/location", to: 'admin/users#location'
  post "/map/users/location", to: 'admin/users#location'
  

  mount RailsAdmin::Engine => '/backend', as: 'rails_admin'
     

  root 'static#index'
  

  

end

RailsApp/app/models/route_stop.rb
# defines a RouteStop and its relation to other objects
class RouteStop < ActiveRecord::Base
  belongs_to :route
  belongs_to :account
  belongs_to :user
  belongs_to :company

  # Gets the location object for a route stop
  def get_location
  	# Find the associated account
  	@account = Account.find(self.account_id)
  	# Hand back a nicely formatted shorthand account location object
  	{ name: @account.name, lat: @account.latitude, lng: @account.longitude }
  end
end

RailsApp/app/controllers/route_stops_controller.rb
class RouteStopsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_route_stop, only: [:show, :edit, :update, :destroy]

  respond_to :html
  
  # Displays a list of Route_stops
  def index
    @route_stops = RouteStop.all
    respond_with(@route_stops)
  end
  
  # displays the Route_stop with the given Route_stop ID
  def show
    respond_with(@route_stop)
  end
  
  # Displays the new Route_stop form to allow the user to enter the Route_stop info
  def new
    @route_id = params[:route_id]
    @routes = Route.where('routes.id' => @route_id)
    @route = @routes.first(:order => 'user_id DESC')
    # this will make sure that only 1 route_stop is added per route.
    @current_stops = RouteStop.where('route_stops.route_id' => @route_id).pluck(:account_id)
    @stop = @current_stops.count
    # by default stop will be 0, and we want it to always start at 1. When they make a new one, it should always be the next number.
    @stop = @stop +1;
    @accounts = Account.where('accounts.User_id' => @current_user.id)
    # this will make sure that only 1 route_stop is added per route.
    if (@stop > 1)
      @accounts = @accounts.where('id not in (?)',@current_stops)
      
    end

    # since we are created a new route, the default stop number should be 1. so if there are no stops, its one. Otherwise add 1 to the amount of stops.
    
    # determines if there are any accounts not already added to route
    if @accounts.count > 0
      @has_account = true
    else
      @has_account = false
    end
        
    
    @route_stop = RouteStop.new
    respond_with(@route_stop)
  end
  
  # Displays the Route_stop form to allow the user to edit the Route_stop info
  def edit
    #Sets the Stop number
    @stop = @route_stop.stop
    #sets accounts still available for this route
    @accounts = Account.where('accounts.User_id' => @route.user_id)
    @has_account = true
  end
  
  # creates a new Route_stop object with the given Parameters
  def create
    @route_stop = RouteStop.new(route_stop_params)
    respond_to do |format|
             if @route_stop.save
               flash[:notice] = flash[:notice].to_a.concat @route_stop.errors.full_messages
               format.html { redirect_to route_path(@route_stop.route_id), :notice => 'Route Stop was successfully added.' }
               format.json { render :json => @route_stop, :status => :created, :location => @route_stop }
             else
               flash[:notice] = flash[:notice].to_a.concat @route_stop.errors.full_messages
               format.html { render :action => "new"}
               format.json { render :json => @route_stop.errors, :status => :unprocessable_entity }
             end
           end
  end
  
  # Updates the given Route_stop with the given parameters from the edit form
  def update
    @route_stop.update(route_stop_params)
    respond_with(@route_stop)
  end
  
  # deletes the given Route_stop object from the DB
  def destroy
    @route_stop.destroy
    respond_with(@route_stop)
  end

  private
    def set_route_stop
      @route_stop = RouteStop.find(params[:id])
      @route = Route.find(@route_stop.route_id)
      @route_id = params[:route_id]
    end

    def route_stop_params
      params.require(:route_stop).permit(:route_id, :account_id, :stop)
    end
end

RailsApp/app/helpers/route_stops_helper.rb
module RouteStopsHelper
end

RailsApp/app/views/route_stops/_form.html.erb
<%= form_for(@route_stop) do |f| %>
Route = <%= @route.name  %>
  <% if @route_stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route_stop.errors.count, "error") %> prohibited this route_stop from being saved:</h2>

      <ul>
      <% @route_stop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.hidden_field :route_id, :value => @route_id %>
	<%= f.hidden_field :stop, :value => @stop %>

  <% if @has_account %>
  <div class="field">
    <%= f.label :account_id %><br>
	<%=	f.collection_select :account_id, @accounts, :id, :name %>
	<div class="actions">
    <%= f.submit %>
  </div>

<% else %>
    <div>
	  You have No Available Accounts to add to this route
	</div>
<% end %>

<% end %>

RailsApp/app/views/route_stops/edit.html.erb
<h1>Editing route_stop</h1>

<%= render 'form' %>

<%= link_to 'Show', @route_stop %> |
<%= link_to 'Back', route_stops_path %>

RailsApp/app/views/route_stops/index.html.erb
<h1>Listing route_stops</h1>

<table>
  <thead>
    <tr>
      <th>Route</th>
      <th>Stop</th>
      <th>Account</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @route_stops.each do |route_stop| %>
      <tr>
        <td><%= route_stop.route.name %></td>
        <td><%= route_stop.stop %></td>
        <td><%= route_stop.account.name %></td>
        <td><%= link_to 'Show', route_stop %></td>
        <td><%= link_to 'Edit', edit_route_stop_path(route_stop) %></td>
        <td><%= link_to 'Destroy', route_stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route stop', new_route_stop_path %>

RailsApp/app/views/route_stops/new.html.erb
<h1>New route_stop</h1>

<%= render 'form' %>

<%= link_to 'Back', @route %>

RailsApp/app/views/route_stops/show.html.erb
<p>
  <strong>Route:</strong>
  <%= @route_stop.route.name %>
</p>

<p>
  <strong>Account:</strong>
  <%= @route_stop.account.name %>
</p>

<p>
  <strong>Stop:</strong>
  <%= @route_stop.stop %>
</p>


<%= link_to 'Edit', edit_route_stop_path(@route_stop) %> |
<%= link_to 'Back', route_stops_path %>